# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bbc939e8c9c7e6ccf52bf723be98ed75b34a480cb382b6edd5d943c963288745404b1d9157cabc9fff4d0e9605ed87ff7122929e91afe86ddf0a0588ebbb07a

test:
  secret_key_base: dbd917fe988bb071de003f9c908b543c592962a3cdb15116fd462df238c2a77dd560c1fe82720dd1ae470ddeb04b26395625d5738cafdcef79c0f9d4d41b51ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
